### PR TITLE
Decode speech

### PR DESCRIPTION
**Pull request by andrewheusser**

### CODE REVIEW

**Comment by jeremymanning** [comment]
just to verify, we're not posting the lab's google cloud API credentials anywhere on the repository, right?

**Comment by jeremymanning** [comment]
also: this looks awesome

**Comment by andrewheusser** [comment]
correct, our credentials are all stored as environmental variables on our local computers, and thats how people should set up to use quail

**Comment by jeremymanning** [comment]
:+1:

**Comment by andrewheusser** [comment]
haha great label! ok i think this is ready to merge

**Comment by jeremymanning** [comment]
yep, merge away...

**Pull request merged**
